version: 2

models:
  - name: customer
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: first_name
        tests:
          - not_null
  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: order_date
        tests:
          - not_null
